package sop_corba;

/**
* sop_corba/AdministradorIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* lunes 18 de junio de 2018 01H14' COT
*/

public final class AdministradorIntHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.AdministradorInt value = null;

  public AdministradorIntHolder ()
  {
  }

  public AdministradorIntHolder (sop_corba.AdministradorInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.AdministradorIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.AdministradorIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.AdministradorIntHelper.type ();
  }

}
