package sop_corba;


/**
* sop_corba/AdministradorIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* lunes 18 de junio de 2018 01H14' COT
*/

public abstract class AdministradorIntPOA extends org.omg.PortableServer.Servant
 implements sop_corba.AdministradorIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarUsuario", new java.lang.Integer (0));
    _methods.put ("listarUsuarios", new java.lang.Integer (1));
    _methods.put ("iniciarSesion", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/AdministradorInt/registrarUsuario
       {
         sop_corba.AdministradorIntPackage.Usuario objUsuario = sop_corba.AdministradorIntPackage.UsuarioHelper.read (in);
         this.registrarUsuario (objUsuario);
         out = $rh.createReply();
         break;
       }

       case 1:  // sop_corba/AdministradorInt/listarUsuarios
       {
         sop_corba.AdministradorIntPackage.Usuario $result[] = null;
         $result = this.listarUsuarios ();
         out = $rh.createReply();
         sop_corba.AdministradorIntPackage.listUsuariosHelper.write (out, $result);
         break;
       }

       case 2:  // sop_corba/AdministradorInt/iniciarSesion
       {
         sop_corba.AdministradorIntPackage.Administrador objAdministrador = sop_corba.AdministradorIntPackage.AdministradorHelper.read (in);
         this.iniciarSesion (objAdministrador);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/AdministradorInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AdministradorInt _this() 
  {
    return AdministradorIntHelper.narrow(
    super._this_object());
  }

  public AdministradorInt _this(org.omg.CORBA.ORB orb) 
  {
    return AdministradorIntHelper.narrow(
    super._this_object(orb));
  }


} // class AdministradorIntPOA
