package sop_corba;


/**
* sop_corba/AdministradorIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* lunes 18 de junio de 2018 01H14' COT
*/

public interface AdministradorIntOperations 
{
  void registrarUsuario (sop_corba.AdministradorIntPackage.Usuario objUsuario);
  sop_corba.AdministradorIntPackage.Usuario[] listarUsuarios ();
  void iniciarSesion (sop_corba.AdministradorIntPackage.Administrador objAdministrador);
} // interface AdministradorIntOperations
