package sop_corba;


/**
* sop_corba/ClienteIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* lunes 18 de junio de 2018 01H14' COT
*/

public interface ClienteIntOperations 
{
  void recibirMensaje (String usuario, String mensaje);
  void establecerSesionPrivada (String usuario);
  void recibirMensajePrivado (String usuario, String mensaje);
  void recibirContacto (String usuario);
  String obtenerNombre ();
  void borrarListaDeContactos ();
  void recibirAudio (byte[] audioStreaming);
} // interface ClienteIntOperations
