package sop_corba;

/**
* sop_corba/ServidorAudioIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* lunes 18 de junio de 2018 01H14' COT
*/

public final class ServidorAudioIntHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ServidorAudioInt value = null;

  public ServidorAudioIntHolder ()
  {
  }

  public ServidorAudioIntHolder (sop_corba.ServidorAudioInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ServidorAudioIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ServidorAudioIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ServidorAudioIntHelper.type ();
  }

}
