package sop_corba;


/**
* sop_corba/ServidorAudioIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* lunes 18 de junio de 2018 01H14' COT
*/

public interface ServidorAudioIntOperations 
{
  boolean registrarCliente (sop_corba.ClienteInt objcllbck, String usuario);
  void enviarMensaje (String usuario, String mensaje);
  boolean desconectarCliente (sop_corba.ClienteInt objcllbck, String usuario);
  sop_corba.ServidorAudioIntPackage.Usuario[] obtenerUsuariosConectados ();
  boolean establecerSesionPriv (String usuario1, String usuario2);
  boolean enviarMensajePriv (String us1, String us2, String mensaje);
  void enviarAudio (sop_corba.ServidorAudioIntPackage.audioHolder audioStreaming);
  void registrarRR ();
} // interface ServidorAudioIntOperations
