package sop_corba.AdministradorIntPackage;


/**
* sop_corba/AdministradorIntPackage/Usuario.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* lunes 18 de junio de 2018 01H14' COT
*/

public final class Usuario implements org.omg.CORBA.portable.IDLEntity
{
  public String nombres = null;
  public String apellidos = null;
  public String nickname = null;
  public String clave = null;

  public Usuario ()
  {
  } // ctor

  public Usuario (String _nombres, String _apellidos, String _nickname, String _clave)
  {
    nombres = _nombres;
    apellidos = _apellidos;
    nickname = _nickname;
    clave = _clave;
  } // ctor

} // class Usuario
